### ISSUE TITLE
Замечания по верстке

### ISSUE THREAD

**Issue by Bezart** [GSemikozov/js-basics-new#2]
Привет, все выглядит отлично, есть только пару замечаний:

1. На табах у меня появляется скролл: https://take.ms/2VFui 
2. При открытии модалки, у страницы пропадает скрол, что приводит к тому что на нижнем слое прыгает контент на несколько пикселей
3. На моб версии, корзина с треугольником должны прилипать

**Comment by GSemikozov** [comment]
1. Так и должно быть, я так понимаю что js фнкционал прокрутки мы не будем реализовывать. Единственное что - можно сделать снизу паддинг размером с полосу прокрутки, чтобы она всегда была ниже контента
2. хм, вроде контент на месте.. можно попросить тебя сделать скрин/видео? И заодно написать какая версия браузера и ос, чтобы я протестил в аналогичных условиях
3. то есть обычный fixed, да? когда скролим, она всегда вверху

**Comment by Bezart** [comment]
1. Мне кажется, проблему скрытия скрола лучше решить через верстку, так как это просто и надежно. Предлагаю сделать 2 контейнера, у родителя поставить `overflow: hidden`, а у внутреннего transform: `translate3d(0px, 0px, 0px);`. Потом при клике на стрелку, у внутреннего контейнера через JS просто менять одно значение `transform: translate3d(-100px, 0px, 0px);` и вся полоса будет двигаться. Таким образом, пользователь никогда не увидит скролбар и не будет проблем с перехватом колесика в некоторых браузерах.

2. Тут по корзинке легко увидеть https://take.ms/HPD0v  
`MacOs, Google ChromeVersion 79.0.3945.130 (Official Build) (64-bit)`

3. Верно. Когда-то с fixed были некоторые проблемы, как альтернативу можно `position: sticky`

**Comment by GSemikozov** [comment]
1. Или так, согласен. Исправил
2. Это происходит потому, что у тебя есть скролбар справа, а когда модалка открывается и мы ставим overflow: hidden на body - полоса прокрутки пропадает, это нормальное поведение. А сам контент - на месте)
3. Готово

**Comment by GSemikozov** [comment]
@Bezart

**Comment by Bezart** [comment]
Отлично, спасибо!
